### ISSUE TITLE
Adding ExternalStorageDirectoryPath in FileSystem?

### ISSUE THREAD

**Issue by abhijeetskadam** [MatheusAlvesA/react-native-androide#3]
Hi Matheus,
first of all thank you for really nice library.

Could you please add absolute external Storage directory path as one more constant in FileSystem module?

If you are OK, I can create PR :-)

Best regards,
Abhijeet

**Comment by MatheusAlvesA** [comment]
Hi, thanks for this Issue.

Unfortunately, the [getExternalStorageDirectory()](https://developer.android.com/reference/android/os/Environment.html#getExternalStorageDirectory()) function is deprecated since the API level 29.  
From the documentation:

> **This method was deprecated in API level 29.**
> To improve user privacy, direct access to shared/external storage devices is deprecated. When an 
> app targets Build.VERSION_CODES.Q, the path returned from this method is no longer directly 
> accessible to apps. Apps can continue to access content stored on shared/external storage by 
> migrating to alternatives such as Context#getExternalFilesDir(String), MediaStore, or 
> Intent#ACTION_OPEN_DOCUMENT.

I'm trying to keep this lib always up to date with the Android system.

If you want, i can add the [ExternalFilesDir](https://developer.android.com/reference/android/content/Context.html#getExternalFilesDir(java.lang.String)). This dir is stored in the external storage, can be accessed by the App, but it's not visible to the user.

**Note:** Like you can see in [this commit](https://github.com/flutter/plugins/pull/1811/commits/25791cdf916427df938c293b7e722ed4ec6a95c1) even the Flutter migrated this path to the new one to avoid deprecated code.

**Comment by abhijeetskadam** [comment]
makes sense, it would be good if you add ExternalFilesDir.

Thank you!

**Comment by MatheusAlvesA** [comment]
Ok, i just released the 1.0.1 version of the lib that includes the `FileSystem.ExternalFilesDir`.

**Comment by abhijeetskadam** [comment]
Thank you @MatheusAlvesA very much!
